language: python
python:
  - '3.6'
  - 'pypy3.5'

install:
  - pip install .

script:
  - flik completion

before_deploy:
  - sed -i "s_version=.*,_version='${TRAVIS_TAG}'_" setup.py

deploy:
  provider: pypi
  user: ${PYPI_USER}
  password: ${PYPI_PASS}
  on:
    tags: true
